<x-layouts.auth title="Set a new password">
    <h1 class="text-2xl font-extrabold">Set a new password</h1>
    <p class="mt-1 text-sm text-muted">Your password was generated by an administrator. Choose your own password before you continue.</p>
    <form method="POST" action="{{ $action }}" class="mt-6 space-y-4">
        @csrf
        <x-password label="New password" autocomplete="new-password" />
        <x-password name="password_confirmation" label="Confirm new password" :policy="false" autocomplete="new-password" />
        <button class="btn-primary w-full btn-pill py-3">Save and continue</button>
    </form>
</x-layouts.auth>
